In [1]:
import pandas as pd
import numpy
import matplotlib as mp

In [12]:
##read .csv file with the data

mobility = pd.read_csv('Global_Mobility_Report_062022.csv', dtype={'sub_region_2': 'str', 'metro_area': 'str', 'iso_3166_2_code': 'str'})
mobility.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0

In [29]:
##Select only information for South Africa

SA = mobility.loc[mobility['country_region_code'] == 'ZA']
SA.tail()

SouthAfrica = SA.iloc[:,[2,9,10,11,12,13,14]]
#SouthAfrica = SA.iloc[:,[2,9:14]]
SouthAfrica.head()

,sub_region_1,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
10199571,NaN,4.0,0.0,-2.0,-2.0,1.0,-2.0
10199572,NaN,-3.0,-1.0,-10.0,-6.0,-1.0,0.0
10199573,NaN,-10.0,-10.0,-10.0,3.0,4.0,1.0
10199574,NaN,-12.0,-12.0,-8.0,0.0,4.0,1.0
10199575,NaN,-12.0,-12.0,-7.0,-2.0,3.0,1.0

In [30]:
##Compare the average change over the period for all the regions.
##I want to get the averages separately
##then save the averages to a table

LP = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Limpopo']
MP = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Mpumalanga']
GP = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Gauteng']
NW = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'North West']
FS = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Free State']
NC = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Nothern Cape']
KZN = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'KwaZulu-Natal']
EC = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Eastern Cape']
WC = SouthAfrica.loc[SouthAfrica['sub_region_1'] == 'Western Cape']
KZN.head()

,sub_region_1,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
10202967,KwaZulu-Natal,-4.0,-2.0,-5.0,-8.0,-1.0,-1.0
10202968,KwaZulu-Natal,-4.0,-3.0,-7.0,-6.0,-2.0,-1.0
10202969,KwaZulu-Natal,-9.0,-6.0,-8.0,3.0,4.0,1.0
10202970,KwaZulu-Natal,-11.0,-12.0,-15.0,1.0,4.0,1.0
10202971,KwaZulu-Natal,-17.0,-17.0,-22.0,-8.0,2.0,4.0

In [37]:
#Get the averages
LA = LP['retail_and_recreation_percent_change_from_baseline'].mean()
MA = MP['retail_and_recreation_percent_change_from_baseline'].mean()
GA = GP['retail_and_recreation_percent_change_from_baseline'].mean()
NWA = NW['retail_and_recreation_percent_change_from_baseline'].mean()
FA = FS['retail_and_recreation_percent_change_from_baseline'].mean()
NCA = NC['retail_and_recreation_percent_change_from_baseline'].mean()
KA = KZN['retail_and_recreation_percent_change_from_baseline'].mean()
EA = EC['retail_and_recreation_percent_change_from_baseline'].mean()
WA = WC['retail_and_recreation_percent_change_from_baseline'].mean()
average = [LA, MA, GA, NWA, FA, NCA, KA, EA, WA]
print(average)

[8.54299175500589, -3.839811542991755, -7.7856301531213195, -0.2826855123674912, -5.65959952885748, nan, -11.88457008244994, -9.521790341578328, -18.511189634864547]

In [38]:
#try doing the two upper cells using lists. Read the book
province = ['Limpopo', 'Mpumalanga', 'Gauteng', 'North West', 'Free State', 'Nothern Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Western Cape']
averages = province[].mean()

TypeError: list indices must be integers or slices, not str

In [ ]:
##Select the region highest, mean and lowest percentage of change over the period.These results should be printed out

In [ ]:
##Draw charts using python to support your answer